version: '3.9'
services:
  angular_app:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - go_service
  
  go_service:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    extra_hosts:
    - "host.docker.internal:host-gateway"
    ports:
      - "9090:9090"
    depends_on:
      - db

  db:
    image: mysql
    ports:
      - "3440:3306"
    environment:
      MYSQL_ROOT_PASSWORD: m1961s97
      MYSQL_DATABASE: gamedatabase
    volumes:
      # - mysql_data:/var/lib/mysql
      - /var/run/mysqld:/host/mysqld
    command: --default-authentication-plugin=mysql_native_password